### PR TITLE
options.mapDbName

### PR DESCRIPTION
**Pull request by gr2m**

### CODE REVIEW

**Comment by gr2m** [comment]
@jo this lets us make database names configurable using a mapDbName option, which can be a key/value object or a map function. Can I haz pretty please? <3

**Comment by gr2m** [comment]
once merged & released, update  
https://github.com/eHealthAfrica/kazana-bootstrap/commit/a3f30224e195a8273de0da30608cc23348b6cbab

**Comment by jo** [comment]
super useful, has tests thanks!

Just needs some docs ;)

**Comment by jo** [comment]
```sh
$ npm publish
+ couchdb-bootstrap@1.8.0
```

**Pull request merged**
